version: "3.8"

services:
  fastapi:
    build:
      context: ./fastapi
    ports:
      - "8000:8000"
    networks:
      - mynetwork

  streamlit:
    build:
      context: ./streamlit
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
    networks:
      - mynetwork

networks:
  mynetwork:
